(define (sum_two_larger a b c)
    (+
        (if (> a b)
            (if (> b c)
                (+ a b)
                (+ a c)
            )
            (if (< a c)
                (+ b c)
                (+ a b)
            )
        )
    )
)

(sum_two_larger 7 5 9)
(sum_two_larger 4 5 9)
(sum_two_larger 4 10 9)
(sum_two_larger 4 10 2)
